name: apotek_bloc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  bloc: ^7.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^7.3.2
  flutter_svg: ^0.23.0+1
  form_field_validator: ^1.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  meta: ^1.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  bloc_test: ^8.4.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets\icons
    - assets\images
  uses-material-design: true

